language: node_js

services:
  - redis-server
  - postgresql

node_js:
  - 6
  - 8

before_script:
  - cp .sample-env .env
  - psql -c 'create database graphql_express;' -U postgres

script:
  - npm run lint
  - npm run test
  - npm run build

cache:
  directories:
    - node_modules
