language: node_js

services:
  - redis-server

node_js:
  - 6
  - 8

before_script:
  - cp .sample-env .env

script:
  - npm run lint
  - npm run test
  - npm run build

cache:
  directories:
    - node_modules
